version: "3.4"

services:
  init:
    build: ./content-init
    image: docker.pkg.github.com/fthkucuk/mcw-continuous-delivery-lab-files/fabrikam-api:main
    depends_on:
      - mongo
    environment:
      MONGODB_CONNECTION: mongodb://mongo:27017/contentdb
